language: python
python:
  - "3.8"

#services:
#  -docker
#
#before_script: pip install docker-compose
env:
  - DJANGO_VERSION=3.0.3

install:
  - pip install djangorestframework
  - pip install -q Django==$DJANGO_VERSION --use-mirrors

script:
  - python manage.py test