language: python
python:
  - "3.8"

#services:
#  -docker
#
#before_script: pip install docker-compose
env:
  - DJANGO_VERSION=1.0.4
  - DJANGO_VERSION=1.1.4
  - DJANGO_VERSION=1.2.7
  - DJANGO_VERSION=1.3.1
  - DJANGO_VERSION=1.

install:
  - pip install -q Django==$DJANGO_VERSION --use-mirrors

script:
  - python manage.py test